#! /bin/bash

# run this in my wsl only and not in Kali VM

# if [ "$#" -ne 3 ]; then
#     echo "usage: $0 <input.md> <input.assets> <input.pdf>"
#     exit
# fi

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <Input.md>"
    exit
fi

input=$1
name="${input%.*}"

markdown_file="$name.md"
assets_dir="$name.assets"
pdf_file="$name.pdf"

# -------- https://github.com/Anu-bhav/Posts  -------- #
backup_dir="/d/Documents/Development/website_github/Posts/"
post_dir="$backup_dir$name"
post_pdf_dir="$backup_dir/PDF/"

mkdir "$post_dir"

for post in "$@"; do
    # if [ -e "$post_dir/$post" ]; then
    #     echo "$post already exists"
    # else
    cp -afr "$post" "$post_dir" && echo "Successfully copied $post to post_dir"
    # fi
done

cp -afr "$pdf_file" $post_pdf_dir && echo "Successfully copied $pdf_file to post_pdf_dir"

cd $backup_dir || return
git add . && git commit -a -m "$name added" && git push
cd - > /dev/null 2>&1 || return
# -------- https://github.com/Anu-bhav/Posts  -------- #


# -------- https://github.com/Anu-bhav/Portfolio-Blog  -------- #
blog_path="/d/Documents/Development/website_github/Portfolio-Blog/src/routes/blog/posts/"
cp -afr "$markdown_file" $blog_path && echo "Successfully copied $markdown_file to blog_path"
# chmod 777 $blog_path/*

static_path="/d/Documents/Development/website_github/Portfolio-Blog/static/"
pdf_path="/d/Documents/Development/website_github/Portfolio-Blog/static/pdf/"
cp -afr "$assets_dir" $static_path && echo "Successfully copied $assets_dir to static_path"
cp -afr "$pdf_file" $pdf_path && echo "Successfully copied $pdf_file to pdf_path"

blog_dir="/d/Documents/Development/website_github/Portfolio-Blog/"
cd $blog_dir || return
git add . && git commit -a -m "new blog post $name added" && git push
cd - > /dev/null 2>&1 || return
# -------- https://github.com/Anu-bhav/Portfolio-Blog  -------- #

